---
name: borracho
on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  setup:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout-source
        uses: actions/checkout@v3
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}

  containerize:
    runs-on: [ ubuntu-latest ]
    needs: setup
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
      - name: podman-build
        run: podman build -t data-analysis:${{ github.sha }} --build-arg MODULE="data-storage" -f Containerfile
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
